const getAppointment = {
  "Status": true,
  "Messages": "",
  "Result": [
    {
      "Id": 358,
      "BookingCode": "2j1zZvK9",
      "UserId": "7LZzgg7ZstX3a9Yuq2ul7xsPRb83",
      "PartnerId": "BwNpYywQKKRUggnYJlkl5x22enn1",
      "StartDate": "2021-07-06T00:00:00+07:00",
      "StartTime": "17:30:00",
      "EndDate": "2021-07-06T00:00:00+07:00",
      "EndTime": "18:00:00",
      "Notes": null,
      "AppointmentStatusId": 4,
      "AppointmentStatusDescription": "ON PROGRESS",
      "ProductServicesId": 10,
      "ProductServiceDescription": "Anxiety Disorder",
      "MasterPriceId": 3,
      "Price": 300000.00,
      "UserFirstName": "Alexander",
      "UserLastName": "Jeanne",
      "UserMobileNumber": "085226750181",
      "UserPictureUrl":
          "https://s3.psykay.co.id/pub/7LZzgg7ZstX3a9Yuq2ul7xsPRb83.png",
      "PartnerPictureUrl":
          "https://s3.psykay.co.id/pub/BwNpYywQKKRUggnYJlkl5x22enn1.png",
      "PartnerFirstName": "Jeanne",
      "PartnerLastName": "Natasya",
      "IsRescheduled": false,
      "RescheduledByUser": false,
      "ReschedulePreId": null,
      "SessionStart": "2021-07-07T00:36:30.342281+07:00",
      "SessionEnd": null,
      "ExpiredDate": "2021-07-07T02:31:23.54352+07:00"
    },
    {
      "Id": 360,
      "BookingCode": "kSk8pYcU",
      "UserId": "7LZzgg7ZstX3a9Yuq2ul7xsPRb83",
      "PartnerId": "BwNpYywQKKRUggnYJlkl5x22enn1",
      "StartDate": "2021-07-06T00:00:00+07:00",
      "StartTime": "18:30:00",
      "EndDate": "2021-07-06T00:00:00+07:00",
      "EndTime": "19:00:00",
      "Notes": "Reschedule",
      "AppointmentStatusId": 7,
      "AppointmentStatusDescription": "RESCHEDULE",
      "ProductServicesId": 10,
      "ProductServiceDescription": "Anxiety Disorder",
      "MasterPriceId": 3,
      "Price": 300000.00,
      "UserFirstName": "Alexander",
      "UserLastName": "Jeanne",
      "UserMobileNumber": "085226750181",
      "UserPictureUrl":
          "https://s3.psykay.co.id/pub/7LZzgg7ZstX3a9Yuq2ul7xsPRb83.png",
      "PartnerPictureUrl":
          "https://s3.psykay.co.id/pub/BwNpYywQKKRUggnYJlkl5x22enn1.png",
      "PartnerFirstName": "Jeanne",
      "PartnerLastName": "Natasya",
      "IsRescheduled": false,
      "RescheduledByUser": false,
      "ReschedulePreId": null,
      "SessionStart": null,
      "SessionEnd": null,
      "ExpiredDate": "2021-07-07T09:35:40.284731+07:00"
    },
    {
      "Id": 362,
      "BookingCode": "kSk8pYcU",
      "UserId": "7LZzgg7ZstX3a9Yuq2ul7xsPRb83",
      "PartnerId": "BwNpYywQKKRUggnYJlkl5x22enn1",
      "StartDate": "2021-07-07T00:00:00+07:00",
      "StartTime": "16:30:00",
      "EndDate": "2021-07-07T00:00:00+07:00",
      "EndTime": "17:00:00",
      "Notes": "Rescheduled from #kSk8pYcU",
      "AppointmentStatusId": 2,
      "AppointmentStatusDescription": "BOOKED",
      "ProductServicesId": 10,
      "ProductServiceDescription": "Anxiety Disorder",
      "MasterPriceId": 3,
      "Price": 300000.00,
      "UserFirstName": "Alexander",
      "UserLastName": "Jeanne",
      "UserMobileNumber": "085226750181",
      "UserPictureUrl":
          "https://s3.psykay.co.id/pub/7LZzgg7ZstX3a9Yuq2ul7xsPRb83.png",
      "PartnerPictureUrl":
          "https://s3.psykay.co.id/pub/BwNpYywQKKRUggnYJlkl5x22enn1.png",
      "PartnerFirstName": "Jeanne",
      "PartnerLastName": "Natasya",
      "IsRescheduled": true,
      "RescheduledByUser": true,
      "ReschedulePreId": 360,
      "SessionStart": null,
      "SessionEnd": null,
      "ExpiredDate": null
    }
  ]
};

const byBookingCode = {
  "Status": true,
  "Messages": "",
  "Result": {
    "StartDateTime": "11:30:00 11:30:00",
    "EndDateTime": "08/05/2021 00.00.00 12:00:00",
    "Id": 3,
    "BookingCode": "WgILfVmr",
    "UserId": "7LZzgg7ZstX3a9Yuq2ul7xsPRb83",
    "PartnerId": "BwNpYywQKKRUggnYJlkl5x22enn1",
    "Price": 200000.00,
    "StartDate": "2021-05-08T00:00:00+07:00",
    "StartTime": "11:30:00",
    "StartTimezone": null,
    "EndDate": "2021-05-08T00:00:00+07:00",
    "EndTime": "12:00:00",
    "EndTimezone": null,
    "AppointmentStatusId": 3,
    "RecurrenceRule": null,
    "Location": null,
    "Notes": null,
    "IsBlock": null,
    "IsAllDay": null,
    "AddDate": "2021-05-07T15:22:55+07:00",
    "AddBy": "7LZzgg7ZstX3a9Yuq2ul7xsPRb83",
    "EditDate": "2021-05-07T15:22:55+07:00",
    "EditBy": "7LZzgg7ZstX3a9Yuq2ul7xsPRb83",
    "ProductServiceId": 2,
    "PriceSchemaId": 2,
    "PartnerPriceId": 149,
    "IsRescheduled": false,
    "RescheduledConfirmed": false,
    "RescheduledBookingCode": null,
    "RescheduledByUser": false,
    "ReschedulePreId": null,
    "IsOnPayment": true,
    "AppointmentStatus": {
      "Id": 3,
      "Name": "CONFIRMED",
      "Description": null,
      "Icon": null,
      "Appointments": []
    },
    "Partner": null,
    "PriceSchema": null,
    "ProductService": null,
    "User": {
      "FullName": "Alexander Jeanne",
      "Id": "7LZzgg7ZstX3a9Yuq2ul7xsPRb83",
      "Email": "alexandervitto116@gmail.com",
      "FirstName": "Alexander",
      "LastName": "Jeanne",
      "Salutation": null,
      "SexId": 1,
      "DateOfBirth": "1991-10-16T00:00:00+07:00",
      "IdentificationNumber": "12312312312",
      "IdentificationTypeId": 2,
      "PhoneNumber": "021 7662727",
      "MobileNumber": "085226750181",
      "Address": "jl. Perkutut 7 no 27",
      "Country": "INDONESIA",
      "Region1": "Jawa Tengah",
      "Region2": "Surakarta (Solo)",
      "Region3": "Pasar Kliwon",
      "Region4": null,
      "ZipCode": "57116",
      "MaritalStatusId": 2,
      "Ethnic": "Jamet",
      "ReligionId": 2,
      "EducationId": 5,
      "OccupationId": 2,
      "PictureUrl":
          "https://s3.psykay.co.id/pub/7LZzgg7ZstX3a9Yuq2ul7xsPRb83.png",
      "AddDate": "0001-01-01T00:00:00+07:07",
      "AddBy": null,
      "EditDate": "2021-05-27T16:34:33.804115+07:00",
      "EditBy": "7LZzgg7ZstX3a9Yuq2ul7xsPRb83",
      "Locality": null,
      "WalletBalance": 0.00,
      "Education": null,
      "IdentificationType": null,
      "MaritalStatus": null,
      "Occupation": null,
      "Religion": null,
      "Sex": null,
      "UserWallet": null,
      "AppointmentRatings": [],
      "Appointments": [],
      "Invoices": [],
      "Payments": [],
      "UserMedicalRecordHistories": [],
      "UserMedicalRecords": [],
      "UserQuestionnaires": [],
      "UserSettings": [],
      "UserVouchers": [],
      "UserWalletTransactions": [],
      "UserWithdrawals": []
    },
    "AppointmentRating": null,
    "InvoiceAppointments": [],
    "PartnerMissedAppointments": [],
    "PaymentAppointments": [],
    "UserMedicalRecordHistories": [],
    "UserMedicalRecords": []
  }
};

const userFreeAppointment = {
  "Status": true,
  "Messages": "Appointment status updated.",
  "Result": [
    {
      "StartDateTime": "00:00:00 00:00:00",
      "EndDateTime": " 00:00:00",
      "Id": 97,
      "BookingCode": null,
      "UserId": "7LZzgg7ZstX3a9Yuq2ul7xsPRb83",
      "PartnerId": null,
      "Price": 200000.00,
      "StartDate": null,
      "StartTime": "00:00:00",
      "StartTimezone": null,
      "EndDate": null,
      "EndTime": "00:00:00",
      "EndTimezone": null,
      "AppointmentStatusId": 8,
      "RecurrenceRule": null,
      "Location": null,
      "Notes": "Reset from #yzawn9bJ",
      "IsBlock": null,
      "IsAllDay": null,
      "AddDate": "2021-06-02T13:31:14+07:00",
      "AddBy": "SYS",
      "EditDate": "2021-06-02T13:31:14+07:00",
      "EditBy": "SYS",
      "ProductServiceId": 128,
      "PriceSchemaId": 2,
      "PartnerPriceId": 149,
      "IsRescheduled": false,
      "RescheduledConfirmed": false,
      "RescheduledBookingCode": "yzawn9bJ",
      "RescheduledByUser": false,
      "ReschedulePreId": 79,
      "IsOnPayment": false,
      "AppointmentStatus": null,
      "Partner": null,
      "PriceSchema": null,
      "ProductService": null,
      "User": null,
      "AppointmentRating": null,
      "InvoiceAppointments": [],
      "PartnerMissedAppointments": [],
      "PaymentAppointments": [],
      "UserMedicalRecordHistories": [],
      "UserMedicalRecords": []
    },
    {
      "StartDateTime": "00:00:00 00:00:00",
      "EndDateTime": " 00:00:00",
      "Id": 98,
      "BookingCode": null,
      "UserId": "7LZzgg7ZstX3a9Yuq2ul7xsPRb83",
      "PartnerId": null,
      "Price": 200000.00,
      "StartDate": null,
      "StartTime": "00:00:00",
      "StartTimezone": null,
      "EndDate": null,
      "EndTime": "00:00:00",
      "EndTimezone": null,
      "AppointmentStatusId": 8,
      "RecurrenceRule": null,
      "Location": null,
      "Notes": "Reset from #EwMvRhmm",
      "IsBlock": null,
      "IsAllDay": null,
      "AddDate": "2021-06-02T13:31:23+07:00",
      "AddBy": "SYS",
      "EditDate": "2021-06-02T13:31:23+07:00",
      "EditBy": "SYS",
      "ProductServiceId": 20,
      "PriceSchemaId": 2,
      "PartnerPriceId": 149,
      "IsRescheduled": false,
      "RescheduledConfirmed": false,
      "RescheduledBookingCode": "EwMvRhmm",
      "RescheduledByUser": false,
      "ReschedulePreId": 57,
      "IsOnPayment": false,
      "AppointmentStatus": null,
      "Partner": null,
      "PriceSchema": null,
      "ProductService": null,
      "User": null,
      "AppointmentRating": null,
      "InvoiceAppointments": [],
      "PartnerMissedAppointments": [],
      "PaymentAppointments": [],
      "UserMedicalRecordHistories": [],
      "UserMedicalRecords": []
    }
  ]
};

const bookAppointment = {
  "Status": true,
  "Messages": "Appointment Created.",
  "Result": {
    "Id": 153,
    "BookingCode": "pkA9XWfF",
    "UserId": "7LZzgg7ZstX3a9Yuq2ul7xsPRb83",
    "PartnerId": "BwNpYywQKKRUggnYJlkl5x22enn1",
    "StartDate": "2021-06-07T00:00:00+07:00",
    "StartTime": "09:30:00",
    "EndDate": "2021-06-07T00:00:00+07:00",
    "EndTime": "10:00:00",
    "AppointmentStatusId": 1,
    "PartnerPriceId": 149,
    "PriceSchemaId": 2,
    "Price": 200000.0,
    "AddDate": "2021-06-03T13:17:18.0644563+07:00",
    "AddBy": "7LZzgg7ZstX3a9Yuq2ul7xsPRb83",
    "EditDate": "2021-06-03T13:17:18.0644573+07:00",
    "EditBy": "7LZzgg7ZstX3a9Yuq2ul7xsPRb83",
    "IsRescheduled": false,
    "RescheduledConfirmed": false,
    "RescheduledByUser": false
  }
};
