const partner = {
  "Status": true,
  "Messages": "",
  "Code": "",
  "Result": {
    "Level": "Madya (10)",
    "YearsOfExperience": 10,
    "FullName": " Jeanne Natasya ",
    "Id": "BwNpYywQKKRUggnYJlkl5x22enn1",
    "Email": "jeanne_natasya@yahoo.com",
    "FirstName": "Jeanne",
    "LastName": "Natasya",
    "Salutation": null,
    "SexId": 2,
    "DateOfBirth": "1980-01-24T00:00:00+07:00",
    "IdentificationNumber": "666655552342",
    "IdentificataionTypeId": 1,
    "PhoneNumber": null,
    "MobileNumber": "+6285215819089",
    "Address": "test address",
    "Country": "Indonesia",
    "Region1": "DKI Jakarta",
    "Region2": "Jakarta Selatan",
    "Region3": "Cilandak",
    "Region4": null,
    "ZipCode": "12440",
    "MaritalStatusId": 1,
    "Ethnic": "NOTSPECIFIED",
    "ReligionId": 7,
    "PictureUrl":
        "https://s3.psykay.co.id/pub/BwNpYywQKKRUggnYJlkl5x22enn1.png",
    "Experiences": 2011,
    "AddDate": "2021-02-02T18:13:00.098783+07:00",
    "AddBy": "ADMIN",
    "EditDate": "2021-02-08T21:15:39.626976+07:00",
    "EditBy": "kECadPbwK0QkU57locDCRFpBIEC3",
    "Locality": "Lebak Bulus",
    "IsSuspended": false,
    "SuspendUntil": null,
    "TitleBack": null,
    "TitleFront": null,
    "IdentificataionType": {
      "Id": 1,
      "Name": "IDENTITY CARD",
      "Description": null,
      "Icon": null,
      "PartnerProfiles": [],
      "UserProfiles": []
    },
    "MaritalStatus": {
      "Id": 1,
      "Name": "SINGLE",
      "Description": null,
      "Icon": "fas fa-frown",
      "PartnerProfiles": [],
      "UserProfiles": []
    },
    "Religion": {
      "Id": 7,
      "Name": "NOTSPECIFIED",
      "Description": null,
      "Icon": null,
      "PartnerProfiles": [],
      "UserProfiles": []
    },
    "Sex": {
      "Id": 2,
      "Name": "FEMALE",
      "Description": null,
      "Icon": "fas fa-venus",
      "PartnerProfiles": [],
      "UserProfiles": []
    },
    "PartnerWallet": null,
    "AppointmentRatings": [],
    "Appointments": [],
    "PartnerBankAccounts": [],
    "PartnerDocuments": [],
    "PartnerExpertises": [
      {
        "Id": 239,
        "PartnerId": "BwNpYywQKKRUggnYJlkl5x22enn1",
        "MasterExpertiseId": 4,
        "ServiceEligible": true,
        "ServiceEnable": true,
        "AddDate": "2021-02-02T18:13:25.027637+07:00",
        "AddBy": "ADMIN",
        "EditDate": "2021-02-02T18:13:25.027637+07:00",
        "EditBy": "ADMIN",
        "MasterExpertise": null
      },
      {
        "Id": 240,
        "PartnerId": "BwNpYywQKKRUggnYJlkl5x22enn1",
        "MasterExpertiseId": 14,
        "ServiceEligible": true,
        "ServiceEnable": true,
        "AddDate": "2021-02-02T18:13:25.027641+07:00",
        "AddBy": "ADMIN",
        "EditDate": "2021-02-02T18:13:25.027641+07:00",
        "EditBy": "ADMIN",
        "MasterExpertise": null
      },
      {
        "Id": 241,
        "PartnerId": "BwNpYywQKKRUggnYJlkl5x22enn1",
        "MasterExpertiseId": 11,
        "ServiceEligible": true,
        "ServiceEnable": true,
        "AddDate": "2021-02-02T18:13:25.027641+07:00",
        "AddBy": "ADMIN",
        "EditDate": "2021-02-02T18:13:25.027641+07:00",
        "EditBy": "ADMIN",
        "MasterExpertise": null
      },
      {
        "Id": 242,
        "PartnerId": "BwNpYywQKKRUggnYJlkl5x22enn1",
        "MasterExpertiseId": 9,
        "ServiceEligible": true,
        "ServiceEnable": true,
        "AddDate": "2021-02-02T18:13:25.02764+07:00",
        "AddBy": "ADMIN",
        "EditDate": "2021-02-02T18:13:25.027641+07:00",
        "EditBy": "ADMIN",
        "MasterExpertise": null
      },
      {
        "Id": 243,
        "PartnerId": "BwNpYywQKKRUggnYJlkl5x22enn1",
        "MasterExpertiseId": 5,
        "ServiceEligible": true,
        "ServiceEnable": true,
        "AddDate": "2021-02-02T18:13:25.02764+07:00",
        "AddBy": "ADMIN",
        "EditDate": "2021-02-02T18:13:25.02764+07:00",
        "EditBy": "ADMIN",
        "MasterExpertise": null
      },
      {
        "Id": 244,
        "PartnerId": "BwNpYywQKKRUggnYJlkl5x22enn1",
        "MasterExpertiseId": 3,
        "ServiceEligible": true,
        "ServiceEnable": true,
        "AddDate": "2021-02-02T18:13:25.02764+07:00",
        "AddBy": "ADMIN",
        "EditDate": "2021-02-02T18:13:25.02764+07:00",
        "EditBy": "ADMIN",
        "MasterExpertise": null
      },
      {
        "Id": 245,
        "PartnerId": "BwNpYywQKKRUggnYJlkl5x22enn1",
        "MasterExpertiseId": 18,
        "ServiceEligible": true,
        "ServiceEnable": true,
        "AddDate": "2021-02-02T18:13:25.027639+07:00",
        "AddBy": "ADMIN",
        "EditDate": "2021-02-02T18:13:25.02764+07:00",
        "EditBy": "ADMIN",
        "MasterExpertise": null
      },
      {
        "Id": 246,
        "PartnerId": "BwNpYywQKKRUggnYJlkl5x22enn1",
        "MasterExpertiseId": 17,
        "ServiceEligible": true,
        "ServiceEnable": true,
        "AddDate": "2021-02-02T18:13:25.027639+07:00",
        "AddBy": "ADMIN",
        "EditDate": "2021-02-02T18:13:25.027639+07:00",
        "EditBy": "ADMIN",
        "MasterExpertise": null
      },
      {
        "Id": 247,
        "PartnerId": "BwNpYywQKKRUggnYJlkl5x22enn1",
        "MasterExpertiseId": 16,
        "ServiceEligible": true,
        "ServiceEnable": true,
        "AddDate": "2021-02-02T18:13:25.027639+07:00",
        "AddBy": "ADMIN",
        "EditDate": "2021-02-02T18:13:25.027639+07:00",
        "EditBy": "ADMIN",
        "MasterExpertise": null
      },
      {
        "Id": 248,
        "PartnerId": "BwNpYywQKKRUggnYJlkl5x22enn1",
        "MasterExpertiseId": 15,
        "ServiceEligible": true,
        "ServiceEnable": true,
        "AddDate": "2021-02-02T18:13:25.027638+07:00",
        "AddBy": "ADMIN",
        "EditDate": "2021-02-02T18:13:25.027638+07:00",
        "EditBy": "ADMIN",
        "MasterExpertise": null
      },
      {
        "Id": 249,
        "PartnerId": "BwNpYywQKKRUggnYJlkl5x22enn1",
        "MasterExpertiseId": 13,
        "ServiceEligible": true,
        "ServiceEnable": true,
        "AddDate": "2021-02-02T18:13:25.027638+07:00",
        "AddBy": "ADMIN",
        "EditDate": "2021-02-02T18:13:25.027638+07:00",
        "EditBy": "ADMIN",
        "MasterExpertise": null
      },
      {
        "Id": 250,
        "PartnerId": "BwNpYywQKKRUggnYJlkl5x22enn1",
        "MasterExpertiseId": 10,
        "ServiceEligible": true,
        "ServiceEnable": true,
        "AddDate": "2021-02-02T18:13:25.027638+07:00",
        "AddBy": "ADMIN",
        "EditDate": "2021-02-02T18:13:25.027638+07:00",
        "EditBy": "ADMIN",
        "MasterExpertise": null
      },
      {
        "Id": 251,
        "PartnerId": "BwNpYywQKKRUggnYJlkl5x22enn1",
        "MasterExpertiseId": 7,
        "ServiceEligible": true,
        "ServiceEnable": true,
        "AddDate": "2021-02-02T18:13:25.027637+07:00",
        "AddBy": "ADMIN",
        "EditDate": "2021-02-02T18:13:25.027637+07:00",
        "EditBy": "ADMIN",
        "MasterExpertise": null
      },
      {
        "Id": 252,
        "PartnerId": "BwNpYywQKKRUggnYJlkl5x22enn1",
        "MasterExpertiseId": 6,
        "ServiceEligible": true,
        "ServiceEnable": true,
        "AddDate": "2021-02-02T18:13:25.027637+07:00",
        "AddBy": "ADMIN",
        "EditDate": "2021-02-02T18:13:25.027637+07:00",
        "EditBy": "ADMIN",
        "MasterExpertise": null
      },
      {
        "Id": 253,
        "PartnerId": "BwNpYywQKKRUggnYJlkl5x22enn1",
        "MasterExpertiseId": 1,
        "ServiceEligible": true,
        "ServiceEnable": true,
        "AddDate": "2021-02-02T18:13:25.027633+07:00",
        "AddBy": "ADMIN",
        "EditDate": "2021-02-02T18:13:25.027635+07:00",
        "EditBy": "ADMIN",
        "MasterExpertise": null
      },
      {
        "Id": 254,
        "PartnerId": "BwNpYywQKKRUggnYJlkl5x22enn1",
        "MasterExpertiseId": 2,
        "ServiceEligible": true,
        "ServiceEnable": true,
        "AddDate": "2021-02-02T18:13:25.027636+07:00",
        "AddBy": "ADMIN",
        "EditDate": "2021-02-02T18:13:25.027637+07:00",
        "EditBy": "ADMIN",
        "MasterExpertise": null
      },
      {
        "Id": 255,
        "PartnerId": "BwNpYywQKKRUggnYJlkl5x22enn1",
        "MasterExpertiseId": 8,
        "ServiceEligible": true,
        "ServiceEnable": true,
        "AddDate": "2021-02-02T18:13:25.027641+07:00",
        "AddBy": "ADMIN",
        "EditDate": "2021-02-02T18:13:25.027641+07:00",
        "EditBy": "ADMIN",
        "MasterExpertise": null
      },
      {
        "Id": 256,
        "PartnerId": "BwNpYywQKKRUggnYJlkl5x22enn1",
        "MasterExpertiseId": 12,
        "ServiceEligible": true,
        "ServiceEnable": true,
        "AddDate": "2021-02-02T18:13:25.027642+07:00",
        "AddBy": "ADMIN",
        "EditDate": "2021-02-02T18:13:25.027642+07:00",
        "EditBy": "ADMIN",
        "MasterExpertise": null
      }
    ],
    "PartnerMissedAppointments": [],
    "PartnerPrices": [
      {
        "Id": 138,
        "PartnerId": "BwNpYywQKKRUggnYJlkl5x22enn1",
        "PriceSchemaId": 4,
        "PriceLevelId": 1,
        "ServiceCategoryId": 2,
        "IsEnabled": false,
        "IsDeleted": false,
        "AddDate": "2021-02-02T18:13:03+07:00",
        "AddBy": "kECadPbwK0QkU57locDCRFpBIEC3",
        "EditDate": "2021-02-02T00:00:00+07:00",
        "EditBy": "kECadPbwK0QkU57locDCRFpBIEC3",
        "PriceSchema": {
          "Id": 4,
          "Name": "VOICE SILVER",
          "Description": null,
          "PriceLevelId": 1,
          "ServiceCategoryId": 2,
          "BasePrice": 150000.00,
          "IsEnabled": false,
          "IsDeleted": false,
          "PriceLevel": null,
          "ServiceCategory": null,
          "PartnerPrices": [],
          "ProductServices": []
        }
      },
      {
        "Id": 139,
        "PartnerId": "BwNpYywQKKRUggnYJlkl5x22enn1",
        "PriceSchemaId": 7,
        "PriceLevelId": 1,
        "ServiceCategoryId": 3,
        "IsEnabled": false,
        "IsDeleted": false,
        "AddDate": "2021-02-02T18:13:03+07:00",
        "AddBy": "kECadPbwK0QkU57locDCRFpBIEC3",
        "EditDate": "2021-02-02T00:00:00+07:00",
        "EditBy": "kECadPbwK0QkU57locDCRFpBIEC3",
        "PriceSchema": {
          "Id": 7,
          "Name": "VIDEO SILVER",
          "Description": null,
          "PriceLevelId": 1,
          "ServiceCategoryId": 3,
          "BasePrice": 200000.00,
          "IsEnabled": false,
          "IsDeleted": false,
          "PriceLevel": null,
          "ServiceCategory": null,
          "PartnerPrices": [],
          "ProductServices": []
        }
      },
      {
        "Id": 149,
        "PartnerId": "BwNpYywQKKRUggnYJlkl5x22enn1",
        "PriceSchemaId": 2,
        "PriceLevelId": 2,
        "ServiceCategoryId": 1,
        "IsEnabled": true,
        "IsDeleted": false,
        "AddDate": "2021-02-24T15:53:21+07:00",
        "AddBy": "BwNpYywQKKRUggnYJlkl5x22enn1",
        "EditDate": "2021-02-24T00:00:00+07:00",
        "EditBy": "BwNpYywQKKRUggnYJlkl5x22enn1",
        "PriceSchema": {
          "Id": 2,
          "Name": "TEXT GOLD",
          "Description": null,
          "PriceLevelId": 2,
          "ServiceCategoryId": 1,
          "BasePrice": 200000.00,
          "IsEnabled": true,
          "IsDeleted": false,
          "PriceLevel": null,
          "ServiceCategory": null,
          "PartnerPrices": [],
          "ProductServices": []
        }
      }
    ],
    "PartnerSchedules": [
      {
        "Id": 138,
        "PartnerId": "BwNpYywQKKRUggnYJlkl5x22enn1",
        "StartDate": null,
        "StartTime": "08:00:00",
        "StartTimezone": null,
        "EndDate": null,
        "EndTime": "12:00:00",
        "EndTimezone": null,
        "EventTypeId": 1,
        "RecurrenceRule": "FREQ=WEEKLY;INTERVAL=1;BYDAY=MO;WKST=MO;",
        "Location": null,
        "IsBlock": false,
        "IsAllDay": false,
        "EffectiveDate": null,
        "IsEnabled": true,
        "IsDeleted": true,
        "AddDate": "2021-02-02T18:17:08.36844+07:00",
        "AddBy": "BwNpYywQKKRUggnYJlkl5x22enn1",
        "EditDate": "2021-02-02T18:17:08.368479+07:00",
        "EditBy": "BwNpYywQKKRUggnYJlkl5x22enn1",
        "EventType": null
      },
      {
        "Id": 139,
        "PartnerId": "BwNpYywQKKRUggnYJlkl5x22enn1",
        "StartDate": null,
        "StartTime": "13:00:00",
        "StartTimezone": null,
        "EndDate": null,
        "EndTime": "19:00:00",
        "EndTimezone": null,
        "EventTypeId": 1,
        "RecurrenceRule": "FREQ=WEEKLY;INTERVAL=1;BYDAY=MO;WKST=MO;",
        "Location": null,
        "IsBlock": false,
        "IsAllDay": false,
        "EffectiveDate": null,
        "IsEnabled": true,
        "IsDeleted": true,
        "AddDate": "2021-02-02T18:17:28.236372+07:00",
        "AddBy": "BwNpYywQKKRUggnYJlkl5x22enn1",
        "EditDate": "2021-02-02T18:17:28.236373+07:00",
        "EditBy": "BwNpYywQKKRUggnYJlkl5x22enn1",
        "EventType": null
      },
      {
        "Id": 140,
        "PartnerId": "BwNpYywQKKRUggnYJlkl5x22enn1",
        "StartDate": null,
        "StartTime": "08:00:00",
        "StartTimezone": null,
        "EndDate": null,
        "EndTime": "20:00:00",
        "EndTimezone": null,
        "EventTypeId": 1,
        "RecurrenceRule": "FREQ=WEEKLY;INTERVAL=1;BYDAY=TU;WKST=MO;",
        "Location": null,
        "IsBlock": false,
        "IsAllDay": false,
        "EffectiveDate": null,
        "IsEnabled": true,
        "IsDeleted": true,
        "AddDate": "2021-02-02T18:17:36.320093+07:00",
        "AddBy": "BwNpYywQKKRUggnYJlkl5x22enn1",
        "EditDate": "2021-02-02T18:17:36.320094+07:00",
        "EditBy": "BwNpYywQKKRUggnYJlkl5x22enn1",
        "EventType": null
      },
      {
        "Id": 141,
        "PartnerId": "BwNpYywQKKRUggnYJlkl5x22enn1",
        "StartDate": null,
        "StartTime": "11:00:00",
        "StartTimezone": null,
        "EndDate": null,
        "EndTime": "20:00:00",
        "EndTimezone": null,
        "EventTypeId": 1,
        "RecurrenceRule": "FREQ=WEEKLY;INTERVAL=1;BYDAY=WE;WKST=MO;",
        "Location": null,
        "IsBlock": false,
        "IsAllDay": false,
        "EffectiveDate": null,
        "IsEnabled": true,
        "IsDeleted": true,
        "AddDate": "2021-02-02T18:17:50.134249+07:00",
        "AddBy": "BwNpYywQKKRUggnYJlkl5x22enn1",
        "EditDate": "2021-02-02T18:17:50.13425+07:00",
        "EditBy": "BwNpYywQKKRUggnYJlkl5x22enn1",
        "EventType": null
      },
      {
        "Id": 142,
        "PartnerId": "BwNpYywQKKRUggnYJlkl5x22enn1",
        "StartDate": null,
        "StartTime": "13:00:00",
        "StartTimezone": null,
        "EndDate": null,
        "EndTime": "19:00:00",
        "EndTimezone": null,
        "EventTypeId": 1,
        "RecurrenceRule": "FREQ=WEEKLY;INTERVAL=1;BYDAY=TH;WKST=MO;",
        "Location": null,
        "IsBlock": false,
        "IsAllDay": false,
        "EffectiveDate": null,
        "IsEnabled": true,
        "IsDeleted": true,
        "AddDate": "2021-02-02T18:18:03.950061+07:00",
        "AddBy": "BwNpYywQKKRUggnYJlkl5x22enn1",
        "EditDate": "2021-02-02T18:18:03.950062+07:00",
        "EditBy": "BwNpYywQKKRUggnYJlkl5x22enn1",
        "EventType": null
      },
      {
        "Id": 143,
        "PartnerId": "BwNpYywQKKRUggnYJlkl5x22enn1",
        "StartDate": null,
        "StartTime": "08:00:00",
        "StartTimezone": null,
        "EndDate": null,
        "EndTime": "20:00:00",
        "EndTimezone": null,
        "EventTypeId": 1,
        "RecurrenceRule": "FREQ=WEEKLY;INTERVAL=1;BYDAY=FR;WKST=MO;",
        "Location": null,
        "IsBlock": false,
        "IsAllDay": false,
        "EffectiveDate": null,
        "IsEnabled": true,
        "IsDeleted": false,
        "AddDate": "2021-02-02T18:18:12.733091+07:00",
        "AddBy": "BwNpYywQKKRUggnYJlkl5x22enn1",
        "EditDate": "2021-02-02T18:18:12.733092+07:00",
        "EditBy": "BwNpYywQKKRUggnYJlkl5x22enn1",
        "EventType": null
      },
      {
        "Id": 178,
        "PartnerId": "BwNpYywQKKRUggnYJlkl5x22enn1",
        "StartDate": null,
        "StartTime": "08:00:00",
        "StartTimezone": null,
        "EndDate": null,
        "EndTime": "20:00:00",
        "EndTimezone": null,
        "EventTypeId": 1,
        "RecurrenceRule": "FREQ=WEEKLY;INTERVAL=1;BYDAY=WE;WKST=MO;",
        "Location": null,
        "IsBlock": false,
        "IsAllDay": false,
        "EffectiveDate": null,
        "IsEnabled": true,
        "IsDeleted": true,
        "AddDate": "2021-02-09T18:02:53.632128+07:00",
        "AddBy": "BwNpYywQKKRUggnYJlkl5x22enn1",
        "EditDate": "2021-02-09T18:02:53.632131+07:00",
        "EditBy": "BwNpYywQKKRUggnYJlkl5x22enn1",
        "EventType": null
      },
      {
        "Id": 179,
        "PartnerId": "BwNpYywQKKRUggnYJlkl5x22enn1",
        "StartDate": null,
        "StartTime": "09:00:00",
        "StartTimezone": null,
        "EndDate": null,
        "EndTime": "12:00:00",
        "EndTimezone": null,
        "EventTypeId": 1,
        "RecurrenceRule": "FREQ=WEEKLY;INTERVAL=1;BYDAY=TH;WKST=MO;",
        "Location": null,
        "IsBlock": false,
        "IsAllDay": false,
        "EffectiveDate": null,
        "IsEnabled": true,
        "IsDeleted": true,
        "AddDate": "2021-02-19T08:38:28.653244+07:00",
        "AddBy": "BwNpYywQKKRUggnYJlkl5x22enn1",
        "EditDate": "2021-02-19T08:38:28.653283+07:00",
        "EditBy": "BwNpYywQKKRUggnYJlkl5x22enn1",
        "EventType": null
      },
      {
        "Id": 180,
        "PartnerId": "BwNpYywQKKRUggnYJlkl5x22enn1",
        "StartDate": null,
        "StartTime": "11:00:00",
        "StartTimezone": null,
        "EndDate": null,
        "EndTime": "17:00:00",
        "EndTimezone": null,
        "EventTypeId": 1,
        "RecurrenceRule": "FREQ=WEEKLY;INTERVAL=1;BYDAY=SA;WKST=MO;",
        "Location": null,
        "IsBlock": false,
        "IsAllDay": false,
        "EffectiveDate": null,
        "IsEnabled": true,
        "IsDeleted": false,
        "AddDate": "2021-02-19T08:38:49.251366+07:00",
        "AddBy": "BwNpYywQKKRUggnYJlkl5x22enn1",
        "EditDate": "2021-02-19T08:38:49.251367+07:00",
        "EditBy": "BwNpYywQKKRUggnYJlkl5x22enn1",
        "EventType": null
      },
      {
        "Id": 181,
        "PartnerId": "BwNpYywQKKRUggnYJlkl5x22enn1",
        "StartDate": null,
        "StartTime": "11:00:00",
        "StartTimezone": null,
        "EndDate": null,
        "EndTime": "14:00:00",
        "EndTimezone": null,
        "EventTypeId": 1,
        "RecurrenceRule": "FREQ=WEEKLY;INTERVAL=1;BYDAY=SU;WKST=MO;",
        "Location": null,
        "IsBlock": false,
        "IsAllDay": false,
        "EffectiveDate": null,
        "IsEnabled": true,
        "IsDeleted": true,
        "AddDate": "2021-02-19T08:39:09.439305+07:00",
        "AddBy": "BwNpYywQKKRUggnYJlkl5x22enn1",
        "EditDate": "2021-02-19T08:39:09.439307+07:00",
        "EditBy": "BwNpYywQKKRUggnYJlkl5x22enn1",
        "EventType": null
      },
      {
        "Id": 204,
        "PartnerId": "BwNpYywQKKRUggnYJlkl5x22enn1",
        "StartDate": null,
        "StartTime": "08:00:00",
        "StartTimezone": null,
        "EndDate": null,
        "EndTime": "15:00:00",
        "EndTimezone": null,
        "EventTypeId": 1,
        "RecurrenceRule": "FREQ=WEEKLY;INTERVAL=1;BYDAY=MO;WKST=MO;",
        "Location": null,
        "IsBlock": false,
        "IsAllDay": false,
        "EffectiveDate": null,
        "IsEnabled": true,
        "IsDeleted": true,
        "AddDate": "2021-04-09T14:48:28.644464+07:00",
        "AddBy": "BwNpYywQKKRUggnYJlkl5x22enn1",
        "EditDate": "2021-04-09T14:48:28.644465+07:00",
        "EditBy": "BwNpYywQKKRUggnYJlkl5x22enn1",
        "EventType": null
      },
      {
        "Id": 205,
        "PartnerId": "BwNpYywQKKRUggnYJlkl5x22enn1",
        "StartDate": null,
        "StartTime": "08:00:00",
        "StartTimezone": null,
        "EndDate": null,
        "EndTime": "14:30:00",
        "EndTimezone": null,
        "EventTypeId": 1,
        "RecurrenceRule": "FREQ=WEEKLY;INTERVAL=1;BYDAY=MO;WKST=MO;",
        "Location": null,
        "IsBlock": false,
        "IsAllDay": false,
        "EffectiveDate": null,
        "IsEnabled": true,
        "IsDeleted": false,
        "AddDate": "2021-04-09T15:31:26.641352+07:00",
        "AddBy": "BwNpYywQKKRUggnYJlkl5x22enn1",
        "EditDate": "2021-04-09T15:31:26.641353+07:00",
        "EditBy": "BwNpYywQKKRUggnYJlkl5x22enn1",
        "EventType": null
      },
      {
        "Id": 206,
        "PartnerId": "BwNpYywQKKRUggnYJlkl5x22enn1",
        "StartDate": null,
        "StartTime": "16:30:00",
        "StartTimezone": null,
        "EndDate": null,
        "EndTime": "18:00:00",
        "EndTimezone": null,
        "EventTypeId": 1,
        "RecurrenceRule": "FREQ=WEEKLY;INTERVAL=1;BYDAY=MO;WKST=MO;",
        "Location": null,
        "IsBlock": false,
        "IsAllDay": false,
        "EffectiveDate": null,
        "IsEnabled": true,
        "IsDeleted": false,
        "AddDate": "2021-04-09T15:46:22.944177+07:00",
        "AddBy": "BwNpYywQKKRUggnYJlkl5x22enn1",
        "EditDate": "2021-04-09T15:46:22.944177+07:00",
        "EditBy": "BwNpYywQKKRUggnYJlkl5x22enn1",
        "EventType": null
      },
      {
        "Id": 207,
        "PartnerId": "BwNpYywQKKRUggnYJlkl5x22enn1",
        "StartDate": null,
        "StartTime": "08:00:00",
        "StartTimezone": null,
        "EndDate": null,
        "EndTime": "17:00:00",
        "EndTimezone": null,
        "EventTypeId": 1,
        "RecurrenceRule": "FREQ=WEEKLY;INTERVAL=1;BYDAY=MO;WKST=MO;",
        "Location": null,
        "IsBlock": false,
        "IsAllDay": false,
        "EffectiveDate": null,
        "IsEnabled": true,
        "IsDeleted": true,
        "AddDate": "2021-04-09T15:46:53.988945+07:00",
        "AddBy": "BwNpYywQKKRUggnYJlkl5x22enn1",
        "EditDate": "2021-04-09T15:46:53.988946+07:00",
        "EditBy": "BwNpYywQKKRUggnYJlkl5x22enn1",
        "EventType": null
      }
    ],
    "PartnerSettings": [],
    "PartnerSuspends": [],
    "PartnerWithdrawRequests": [],
    "UserMedicalRecordHistories": [],
    "UserMedicalRecords": []
  }
};

const detailByExpertise = {
  "Status": true,
  "Messages": "",
  "Result": {
    "PartnerId": "BwNpYywQKKRUggnYJlkl5x22enn1",
    "FirstName": "Jeanne",
    "LastName": "Natasya",
    "MasterExpertiseId": 7,
    "PriceSchemaId": 2,
    "PriceName": "SILVER VOICE",
    "ServiceId": 56,
    "ServiceName": "Eating Disorder",
    "ServicePrice": 150000.00
  }
};

const price = {
  "Status": true,
  "Messages": "",
  "Code": "",
  "Result": [
    {
      "Id": 149,
      "PartnerId": "BwNpYywQKKRUggnYJlkl5x22enn1",
      "MasterPriceId": 2,
      "PriceCategoryId": 0,
      "PriceName": "TEXT GOLD",
      "Price": 200000.00,
      "PriceSchemaId": 0,
      "PriceSchemaName": null,
      "PriceLevelId": 0,
      "PriceLevelname": null,
      "ServiceCategoryId": 0,
      "ServiceCategoryName": null,
      "SessionCount": 0
    }
  ]
};

const schedule = {
  "Status": true,
  "Messages": "",
  "Code": "",
  "Result": [
    {
      "Id": 143,
      "PartnerId": "BwNpYywQKKRUggnYJlkl5x22enn1",
      "StartDate": null,
      "StartTime": "08:00:00",
      "StartTimezone": null,
      "EndDate": null,
      "EndTime": "20:00:00",
      "EndTimezone": null,
      "EventTypeId": 1,
      "RecurrenceRule": "FREQ=WEEKLY;INTERVAL=1;BYDAY=FR;WKST=MO;",
      "Location": null,
      "IsBlock": false,
      "IsAllDay": false
    },
    {
      "Id": 180,
      "PartnerId": "BwNpYywQKKRUggnYJlkl5x22enn1",
      "StartDate": null,
      "StartTime": "11:00:00",
      "StartTimezone": null,
      "EndDate": null,
      "EndTime": "17:00:00",
      "EndTimezone": null,
      "EventTypeId": 1,
      "RecurrenceRule": "FREQ=WEEKLY;INTERVAL=1;BYDAY=SA;WKST=MO;",
      "Location": null,
      "IsBlock": false,
      "IsAllDay": false
    },
    {
      "Id": 205,
      "PartnerId": "BwNpYywQKKRUggnYJlkl5x22enn1",
      "StartDate": null,
      "StartTime": "08:00:00",
      "StartTimezone": null,
      "EndDate": null,
      "EndTime": "14:30:00",
      "EndTimezone": null,
      "EventTypeId": 1,
      "RecurrenceRule": "FREQ=WEEKLY;INTERVAL=1;BYDAY=MO;WKST=MO;",
      "Location": null,
      "IsBlock": false,
      "IsAllDay": false
    },
    {
      "Id": 206,
      "PartnerId": "BwNpYywQKKRUggnYJlkl5x22enn1",
      "StartDate": null,
      "StartTime": "16:30:00",
      "StartTimezone": null,
      "EndDate": null,
      "EndTime": "18:00:00",
      "EndTimezone": null,
      "EventTypeId": 1,
      "RecurrenceRule": "FREQ=WEEKLY;INTERVAL=1;BYDAY=MO;WKST=MO;",
      "Location": null,
      "IsBlock": false,
      "IsAllDay": false
    }
  ]
};

const rescheduleResource = {
  "Status": true,
  "Messages": "",
  "Code": "",
  "Result": [
    {
      "Id": 143,
      "PartnerId": "BwNpYywQKKRUggnYJlkl5x22enn1",
      "StartDate": null,
      "StartTime": "08:00:00",
      "StartTimezone": null,
      "EndDate": null,
      "EndTime": "20:00:00",
      "EndTimezone": null,
      "EventTypeId": 1,
      "RecurrenceRule": "FREQ=WEEKLY;INTERVAL=1;BYDAY=FR;WKST=MO;",
      "Location": null,
      "IsBlock": false,
      "IsAllDay": false
    },
    {
      "Id": 180,
      "PartnerId": "BwNpYywQKKRUggnYJlkl5x22enn1",
      "StartDate": null,
      "StartTime": "11:00:00",
      "StartTimezone": null,
      "EndDate": null,
      "EndTime": "17:00:00",
      "EndTimezone": null,
      "EventTypeId": 1,
      "RecurrenceRule": "FREQ=WEEKLY;INTERVAL=1;BYDAY=SA;WKST=MO;",
      "Location": null,
      "IsBlock": false,
      "IsAllDay": false
    },
    {
      "Id": 205,
      "PartnerId": "BwNpYywQKKRUggnYJlkl5x22enn1",
      "StartDate": null,
      "StartTime": "08:00:00",
      "StartTimezone": null,
      "EndDate": null,
      "EndTime": "14:30:00",
      "EndTimezone": null,
      "EventTypeId": 1,
      "RecurrenceRule": "FREQ=WEEKLY;INTERVAL=1;BYDAY=MO;WKST=MO;",
      "Location": null,
      "IsBlock": false,
      "IsAllDay": false
    },
    {
      "Id": 206,
      "PartnerId": "BwNpYywQKKRUggnYJlkl5x22enn1",
      "StartDate": null,
      "StartTime": "16:30:00",
      "StartTimezone": null,
      "EndDate": null,
      "EndTime": "18:00:00",
      "EndTimezone": null,
      "EventTypeId": 1,
      "RecurrenceRule": "FREQ=WEEKLY;INTERVAL=1;BYDAY=MO;WKST=MO;",
      "Location": null,
      "IsBlock": false,
      "IsAllDay": false
    }
  ]
};
