const openPayment = {
  "Status": true,
  "Messages": "",
  "Code": "",
  "Result": [
    {
      "Id": 38,
      "InvoiceNumber": "PAY/2021/06/03/00001",
      "PaymentMethodId": 2,
      "OrderId": null,
      "TransactionId": null,
      "TransactionTime": null,
      "TransactionStatus": 1,
      "StatusCode": null,
      "StatusMessage": null,
      "PaymentTime": null,
      "PaymentType": null,
      "ApprovalTime": null,
      "ApprovalBy": null,
      "ToAccountNumber": null,
      "ToAccountName": null,
      "ToBankCode": null,
      "FromAccountNumber": null,
      "FromAccountName": null,
      "FromBankCode": null,
      "PaymentNotes": null,
      "GrossAmount": 200000.00,
      "PaidAmount": null,
      "PaymentBalance": null,
      "SignatureKey": null,
      "MerchantId": null,
      "FraudStatus": null,
      "Currency": null,
      "MaskedCard": null,
      "Eci": null,
      "ChannelResponseMessage": null,
      "ChannelResponseCode": null,
      "CardType": null,
      "BillKey": null,
      "BillerCode": null,
      "PaymentCode": null,
      "Store": null,
      "AddBy": null,
      "AddDate": null,
      "EditBy": null,
      "EditDate": null,
      "DataFlag": 0,
      "ApprovalCode": null,
      "UserId": "7LZzgg7ZstX3a9Yuq2ul7xsPRb83",
      "PaymentRefcode": null,
      "ApprovalRefcode": null,
      "ApprovalNotes": null,
      "FromBankCodeNavigation": null,
      "PaymentMethod": null,
      "ToBankCodeNavigation": null,
      "TransactionStatusNavigation": null,
      "User": null,
      "PaymentAppointments": [
        {
          "Id": 57,
          "AppointmentId": 153,
          "PaymentId": 38,
          "Appointment": {
            "StartDateTime": "09:30:00 09:30:00",
            "EndDateTime": "07/06/2021 00.00.00 10:00:00",
            "Id": 153,
            "BookingCode": "pkA9XWfF",
            "UserId": "7LZzgg7ZstX3a9Yuq2ul7xsPRb83",
            "PartnerId": "BwNpYywQKKRUggnYJlkl5x22enn1",
            "Price": 200000.00,
            "StartDate": "2021-06-07T00:00:00+07:00",
            "StartTime": "09:30:00",
            "StartTimezone": null,
            "EndDate": "2021-06-07T00:00:00+07:00",
            "EndTime": "10:00:00",
            "EndTimezone": null,
            "AppointmentStatusId": 1,
            "RecurrenceRule": null,
            "Location": null,
            "Notes": null,
            "IsBlock": null,
            "IsAllDay": null,
            "AddDate": "2021-06-03T13:17:18+07:00",
            "AddBy": "7LZzgg7ZstX3a9Yuq2ul7xsPRb83",
            "EditDate": "2021-06-03T13:17:18+07:00",
            "EditBy": "7LZzgg7ZstX3a9Yuq2ul7xsPRb83",
            "ProductServiceId": 155,
            "PriceSchemaId": 2,
            "PartnerPriceId": 149,
            "IsRescheduled": false,
            "RescheduledConfirmed": false,
            "RescheduledBookingCode": null,
            "RescheduledByUser": false,
            "ReschedulePreId": null,
            "IsOnPayment": true,
            "AppointmentStatus": null,
            "Partner": null,
            "PriceSchema": null,
            "ProductService": null,
            "User": null,
            "AppointmentRating": null,
            "InvoiceAppointments": [],
            "PartnerMissedAppointments": [],
            "PaymentAppointments": [],
            "UserMedicalRecordHistories": [],
            "UserMedicalRecords": []
          }
        }
      ]
    },
    {
      "Id": 41,
      "InvoiceNumber": "PAY/2021/06/04/00001",
      "PaymentMethodId": 1,
      "OrderId": "7affa3dc-40cd-4c30-a418-483479009220",
      "TransactionId": null,
      "TransactionTime": null,
      "TransactionStatus": 1,
      "StatusCode": null,
      "StatusMessage": null,
      "PaymentTime": null,
      "PaymentType": "bank_transfer",
      "ApprovalTime": null,
      "ApprovalBy": null,
      "ToAccountNumber": "15627695066",
      "ToAccountName": null,
      "ToBankCode": "014",
      "FromAccountNumber": null,
      "FromAccountName": null,
      "FromBankCode": null,
      "PaymentNotes": null,
      "GrossAmount": 200000.00,
      "PaidAmount": null,
      "PaymentBalance": null,
      "SignatureKey": null,
      "MerchantId": null,
      "FraudStatus": null,
      "Currency": null,
      "MaskedCard": null,
      "Eci": null,
      "ChannelResponseMessage": null,
      "ChannelResponseCode": null,
      "CardType": null,
      "BillKey": null,
      "BillerCode": null,
      "PaymentCode": null,
      "Store": null,
      "AddBy": null,
      "AddDate": null,
      "EditBy": null,
      "EditDate": null,
      "DataFlag": 0,
      "ApprovalCode": null,
      "UserId": "7LZzgg7ZstX3a9Yuq2ul7xsPRb83",
      "PaymentRefcode": null,
      "ApprovalRefcode": null,
      "ApprovalNotes": null,
      "FromBankCodeNavigation": null,
      "PaymentMethod": null,
      "ToBankCodeNavigation": null,
      "TransactionStatusNavigation": null,
      "User": null,
      "PaymentAppointments": [
        {
          "Id": 60,
          "AppointmentId": 157,
          "PaymentId": 41,
          "Appointment": {
            "StartDateTime": "12:30:00 12:30:00",
            "EndDateTime": "12/06/2021 00.00.00 13:00:00",
            "Id": 157,
            "BookingCode": "YxCmBaQK",
            "UserId": "7LZzgg7ZstX3a9Yuq2ul7xsPRb83",
            "PartnerId": "BwNpYywQKKRUggnYJlkl5x22enn1",
            "Price": 200000.00,
            "StartDate": "2021-06-12T00:00:00+07:00",
            "StartTime": "12:30:00",
            "StartTimezone": null,
            "EndDate": "2021-06-12T00:00:00+07:00",
            "EndTime": "13:00:00",
            "EndTimezone": null,
            "AppointmentStatusId": 1,
            "RecurrenceRule": null,
            "Location": null,
            "Notes": null,
            "IsBlock": null,
            "IsAllDay": null,
            "AddDate": "2021-06-04T11:40:26+07:00",
            "AddBy": "7LZzgg7ZstX3a9Yuq2ul7xsPRb83",
            "EditDate": "2021-06-04T11:40:26+07:00",
            "EditBy": "7LZzgg7ZstX3a9Yuq2ul7xsPRb83",
            "ProductServiceId": 20,
            "PriceSchemaId": 2,
            "PartnerPriceId": 149,
            "IsRescheduled": false,
            "RescheduledConfirmed": false,
            "RescheduledBookingCode": null,
            "RescheduledByUser": false,
            "ReschedulePreId": null,
            "IsOnPayment": true,
            "AppointmentStatus": null,
            "Partner": null,
            "PriceSchema": null,
            "ProductService": null,
            "User": null,
            "AppointmentRating": null,
            "InvoiceAppointments": [],
            "PartnerMissedAppointments": [],
            "PaymentAppointments": [],
            "UserMedicalRecordHistories": [],
            "UserMedicalRecords": []
          }
        }
      ]
    }
  ]
};

const pending = {
  "Status": true,
  "Messages": "",
  "Code": "",
  "Result": [
    {
      "Id": 40,
      "InvoiceNumber": "PAY/2021/06/03/00003",
      "PaymentMethodId": 1,
      "OrderId": "61549653-7cfe-4b08-8ea7-9bcfd5237034",
      "TransactionId": "f092f31b-bbdd-4801-95f4-3100c58904e9",
      "TransactionTime": "2021-06-03T14:44:59+07:00",
      "TransactionStatus": 2,
      "StatusCode": "200",
      "StatusMessage": "midtrans payment notification",
      "PaymentTime": null,
      "PaymentType": "bank_transfer",
      "ApprovalTime": null,
      "ApprovalBy": null,
      "ToAccountNumber": "15627841277",
      "ToAccountName": null,
      "ToBankCode": "014",
      "FromAccountNumber": null,
      "FromAccountName": null,
      "FromBankCode": null,
      "PaymentNotes": null,
      "GrossAmount": 200000.00,
      "PaidAmount": null,
      "PaymentBalance": null,
      "SignatureKey":
          "0aeb4ca516d00ec50bc5494eb5bb1158abbb4e633a0f88a26a01c4619e86392ad10439471b1924c364d01ba1f34cf1e57c474f7d6e8c0829180f8dd129084f1e",
      "MerchantId": "G873415627",
      "FraudStatus": "accept",
      "Currency": "IDR",
      "MaskedCard": null,
      "Eci": null,
      "ChannelResponseMessage": null,
      "ChannelResponseCode": null,
      "CardType": null,
      "BillKey": null,
      "BillerCode": null,
      "PaymentCode": null,
      "Store": null,
      "AddBy": null,
      "AddDate": null,
      "EditBy": null,
      "EditDate": null,
      "DataFlag": 1,
      "ApprovalCode": null,
      "UserId": "7LZzgg7ZstX3a9Yuq2ul7xsPRb83",
      "PaymentRefcode": null,
      "ApprovalRefcode": null,
      "ApprovalNotes": null,
      "FromBankCodeNavigation": null,
      "PaymentMethod": null,
      "ToBankCodeNavigation": null,
      "TransactionStatusNavigation": null,
      "User": null,
      "PaymentAppointments": [
        {
          "Id": 59,
          "AppointmentId": 155,
          "PaymentId": 40,
          "IsDelete": false,
          "Appointment": {
            "StartDateTime": "Sabtu, 12 Juni 2021 12:00:00",
            "EndDateTime": "Sabtu, 12 Juni 2021 12:30:00",
            "Id": 155,
            "BookingCode": "dQwQrtep",
            "UserId": "7LZzgg7ZstX3a9Yuq2ul7xsPRb83",
            "PartnerId": "BwNpYywQKKRUggnYJlkl5x22enn1",
            "Price": 200000.00,
            "StartDate": "2021-06-12T00:00:00+07:00",
            "StartTime": "12:00:00",
            "StartTimezone": null,
            "EndDate": "2021-06-12T00:00:00+07:00",
            "EndTime": "12:30:00",
            "EndTimezone": null,
            "AppointmentStatusId": 1,
            "RecurrenceRule": null,
            "Location": null,
            "Notes": null,
            "IsBlock": null,
            "IsAllDay": null,
            "AddDate": "2021-06-03T14:44:43+07:00",
            "AddBy": "7LZzgg7ZstX3a9Yuq2ul7xsPRb83",
            "EditDate": "2021-06-03T14:44:43+07:00",
            "EditBy": "7LZzgg7ZstX3a9Yuq2ul7xsPRb83",
            "ProductServiceId": 155,
            "PriceSchemaId": 2,
            "PartnerPriceId": 149,
            "IsRescheduled": false,
            "RescheduledConfirmed": false,
            "RescheduledBookingCode": null,
            "RescheduledByUser": false,
            "ReschedulePreId": null,
            "IsOnPayment": true,
            "AppointmentStatus": null,
            "Partner": null,
            "PriceSchema": null,
            "ProductService": null,
            "User": null,
            "AppointmentRating": null,
            "InvoiceAppointments": [],
            "PartnerMissedAppointments": [],
            "PaymentAppointments": [],
            "UserMedicalRecordHistories": [],
            "UserMedicalRecords": []
          }
        }
      ]
    }
  ]
};

const settled = [
  {
    "Id": 1,
    "InvoiceNumber": "PAY/2021/05/07/00001",
    "PaymentMethodId": 1,
    "OrderId": "c98df624-3346-456a-adc7-da32624232ce",
    "TransactionId": "0aabcef5-6905-4bc0-9bed-8cb50221a557",
    "TransactionTime": "2021-05-07T14:59:17+07:00",
    "TransactionStatus": 3,
    "StatusCode": "201",
    "StatusMessage": "midtrans payment notification",
    "PaymentTime": null,
    "PaymentType": "bank_transfer",
    "ApprovalTime": null,
    "ApprovalBy": null,
    "ToAccountNumber": "15627359960",
    "ToAccountName": null,
    "ToBankCode": "014",
    "FromAccountNumber": null,
    "FromAccountName": null,
    "FromBankCode": null,
    "PaymentNotes": null,
    "GrossAmount": 200000.00,
    "PaidAmount": null,
    "PaymentBalance": null,
    "SignatureKey":
        "e8b40283ae83ea2b411ff81abbbc90ac3ebd629c1d15e1ae1f12dba0a9d966ae43273ec6b099bbbf710a5f62f4fdf0fb77fb58560fc08d472027597b10654b94",
    "MerchantId": "G873415627",
    "FraudStatus": "accept",
    "Currency": "IDR",
    "MaskedCard": null,
    "Eci": null,
    "ChannelResponseMessage": null,
    "ChannelResponseCode": null,
    "CardType": null,
    "BillKey": null,
    "BillerCode": null,
    "PaymentCode": null,
    "Store": null,
    "AddBy": null,
    "AddDate": null,
    "EditBy": null,
    "EditDate": null,
    "DataFlag": 1,
    "ApprovalCode": null,
    "UserId": "7LZzgg7ZstX3a9Yuq2ul7xsPRb83",
    "PaymentRefcode": null,
    "ApprovalRefcode": null,
    "ApprovalNotes": null,
    "FromBankCodeNavigation": null,
    "PaymentMethod": null,
    "ToBankCodeNavigation": null,
    "TransactionStatusNavigation": null,
    "User": null,
    "PaymentAppointments": [
      {
        "Id": 1,
        "AppointmentId": 1,
        "PaymentId": 1,
        "IsDelete": false,
        "Appointment": {
          "StartDateTime": "Jumat, 07 Mei 2021 20:00:00",
          "EndDateTime": "Jumat, 07 Mei 2021 20:30:00",
          "Id": 1,
          "BookingCode": "J52twCiw",
          "UserId": "7LZzgg7ZstX3a9Yuq2ul7xsPRb83",
          "PartnerId": "BwNpYywQKKRUggnYJlkl5x22enn1",
          "Price": 200000.00,
          "StartDate": "2021-05-07T00:00:00+07:00",
          "StartTime": "20:00:00",
          "StartTimezone": null,
          "EndDate": "2021-05-07T00:00:00+07:00",
          "EndTime": "20:30:00",
          "EndTimezone": null,
          "AppointmentStatusId": 3,
          "RecurrenceRule": null,
          "Location": null,
          "Notes": null,
          "IsBlock": null,
          "IsAllDay": null,
          "AddDate": "2021-05-07T15:23:04+07:00",
          "AddBy": "7LZzgg7ZstX3a9Yuq2ul7xsPRb83",
          "EditDate": "2021-05-07T15:23:04+07:00",
          "EditBy": "7LZzgg7ZstX3a9Yuq2ul7xsPRb83",
          "ProductServiceId": 137,
          "PriceSchemaId": 2,
          "PartnerPriceId": 149,
          "IsRescheduled": false,
          "RescheduledConfirmed": false,
          "RescheduledBookingCode": null,
          "RescheduledByUser": false,
          "ReschedulePreId": null,
          "IsOnPayment": true,
          "AppointmentStatus": null,
          "Partner": null,
          "PriceSchema": null,
          "ProductService": null,
          "User": null,
          "AppointmentRating": null,
          "InvoiceAppointments": [],
          "PartnerMissedAppointments": [],
          "PaymentAppointments": [],
          "UserMedicalRecordHistories": [],
          "UserMedicalRecords": []
        }
      }
    ]
  },
  {
    "Id": 14,
    "InvoiceNumber": "PAY/2021/05/20/00003",
    "PaymentMethodId": 1,
    "OrderId": "7ed34c63-3870-4415-a99c-698cd2b6e58c",
    "TransactionId": "10546e4d-9480-4a4d-b37f-a322ec6dff9a",
    "TransactionTime": "2021-05-20T16:13:39+07:00",
    "TransactionStatus": 3,
    "StatusCode": "201",
    "StatusMessage": "midtrans payment notification",
    "PaymentTime": null,
    "PaymentType": "bank_transfer",
    "ApprovalTime": null,
    "ApprovalBy": null,
    "ToAccountNumber": "15627221231",
    "ToAccountName": null,
    "ToBankCode": "014",
    "FromAccountNumber": null,
    "FromAccountName": null,
    "FromBankCode": null,
    "PaymentNotes": null,
    "GrossAmount": 200000.00,
    "PaidAmount": null,
    "PaymentBalance": null,
    "SignatureKey":
        "33bdbdcf42a5754cf6dc5784d7d32aa20e8f52efd7c1910ef5daa80b7c68178a745facc168eceb9971d577e6cc22b6c72084a0442991a4e225a38fd9f952cd0e",
    "MerchantId": "G873415627",
    "FraudStatus": "accept",
    "Currency": "IDR",
    "MaskedCard": null,
    "Eci": null,
    "ChannelResponseMessage": null,
    "ChannelResponseCode": null,
    "CardType": null,
    "BillKey": null,
    "BillerCode": null,
    "PaymentCode": null,
    "Store": null,
    "AddBy": null,
    "AddDate": null,
    "EditBy": null,
    "EditDate": null,
    "DataFlag": 1,
    "ApprovalCode": null,
    "UserId": "7LZzgg7ZstX3a9Yuq2ul7xsPRb83",
    "PaymentRefcode": null,
    "ApprovalRefcode": null,
    "ApprovalNotes": null,
    "FromBankCodeNavigation": null,
    "PaymentMethod": null,
    "ToBankCodeNavigation": null,
    "TransactionStatusNavigation": null,
    "User": null,
    "PaymentAppointments": [
      {
        "Id": 14,
        "AppointmentId": 39,
        "PaymentId": 14,
        "IsDelete": false,
        "Appointment": {
          "StartDateTime": "Sabtu, 29 Mei 2021 15:30:00",
          "EndDateTime": "Sabtu, 29 Mei 2021 16:00:00",
          "Id": 39,
          "BookingCode": "KjcjbDpC",
          "UserId": "7LZzgg7ZstX3a9Yuq2ul7xsPRb83",
          "PartnerId": "BwNpYywQKKRUggnYJlkl5x22enn1",
          "Price": 200000.00,
          "StartDate": "2021-05-29T00:00:00+07:00",
          "StartTime": "15:30:00",
          "StartTimezone": null,
          "EndDate": "2021-05-29T00:00:00+07:00",
          "EndTime": "16:00:00",
          "EndTimezone": null,
          "AppointmentStatusId": 7,
          "RecurrenceRule": null,
          "Location": null,
          "Notes": "Reschedule",
          "IsBlock": null,
          "IsAllDay": null,
          "AddDate": "2021-05-20T16:13:18+07:00",
          "AddBy": "7LZzgg7ZstX3a9Yuq2ul7xsPRb83",
          "EditDate": "2021-05-20T16:21:41+07:00",
          "EditBy": "BwNpYywQKKRUggnYJlkl5x22enn1",
          "ProductServiceId": 128,
          "PriceSchemaId": 2,
          "PartnerPriceId": 149,
          "IsRescheduled": false,
          "RescheduledConfirmed": false,
          "RescheduledBookingCode": null,
          "RescheduledByUser": false,
          "ReschedulePreId": null,
          "IsOnPayment": true,
          "AppointmentStatus": null,
          "Partner": null,
          "PriceSchema": null,
          "ProductService": null,
          "User": null,
          "AppointmentRating": null,
          "InvoiceAppointments": [],
          "PartnerMissedAppointments": [],
          "PaymentAppointments": [],
          "UserMedicalRecordHistories": [],
          "UserMedicalRecords": []
        }
      }
    ]
  }
];

const initPayment = {
  "Status": true,
  "Messages": "",
  "Code": "",
  "Result": {
    "Id": 86,
    "InvoiceNumber": "PAY/2021/06/22/00008",
    "PaymentMethodId": 2,
    "OrderId": null,
    "TransactionId": null,
    "TransactionTime": null,
    "TransactionStatus": 1,
    "StatusCode": null,
    "StatusMessage": null,
    "PaymentTime": null,
    "PaymentType": null,
    "ApprovalTime": null,
    "ApprovalBy": null,
    "ToAccountNumber": null,
    "ToAccountName": null,
    "ToBankCode": null,
    "FromAccountNumber": null,
    "FromAccountName": null,
    "FromBankCode": null,
    "PaymentNotes": null,
    "GrossAmount": 200000.0,
    "PaidAmount": null,
    "PaymentBalance": null,
    "SignatureKey": null,
    "MerchantId": null,
    "FraudStatus": null,
    "Currency": null,
    "MaskedCard": null,
    "Eci": null,
    "ChannelResponseMessage": null,
    "ChannelResponseCode": null,
    "CardType": null,
    "BillKey": null,
    "BillerCode": null,
    "PaymentCode": null,
    "Store": null,
    "AddBy": null,
    "AddDate": null,
    "EditBy": null,
    "EditDate": null,
    "DataFlag": 0,
    "ApprovalCode": null,
    "UserId": "7LZzgg7ZstX3a9Yuq2ul7xsPRb83",
    "PaymentRefcode": null,
    "ApprovalRefcode": null,
    "ApprovalNotes": null,
    "FromBankCodeNavigation": null,
    "PaymentMethod": null,
    "ToBankCodeNavigation": null,
    "TransactionStatusNavigation": null,
    "User": null,
    "PaymentAppointments": [
      {
        "Id": 148,
        "AppointmentId": 194,
        "PaymentId": 86,
        "IsDelete": false,
        "Appointment": null
      }
    ]
  }
};
