const productService = {
  "Status": true,
  "Messages": "",
  "Code": "",
  "Result": [
    {
      "Id": 62,
      "Name": "Eating Disorder",
      "Description": null,
      "MasterExpertiseId": 7,
      "PriceSchemaId": 8,
      "IsBundled": false,
      "BundleParentId": null,
      "SellingPrice": 250000.00,
      "ProductCount": 1,
      "IsEnabled": true,
      "IsDeleted": false,
      "StartDate": null,
      "EndDate": null,
      "AddDate": "2020-09-29T13:43:42.849854+07:00",
      "AddBy": null,
      "EditDate": null,
      "EditBy": null,
      "BundleParent": null,
      "MasterExpertise": null,
      "PriceSchema": null,
      "Appointments": [],
      "InverseBundleParent": [],
      "InvoiceDetails": []
    },
    {
      "Id": 8,
      "Name": "Child & Teen Development",
      "Description": null,
      "MasterExpertiseId": 1,
      "PriceSchemaId": 8,
      "IsBundled": false,
      "BundleParentId": null,
      "SellingPrice": 250000.00,
      "ProductCount": 1,
      "IsEnabled": true,
      "IsDeleted": false,
      "StartDate": null,
      "EndDate": null,
      "AddDate": "2020-09-29T13:26:36.14188+07:00",
      "AddBy": null,
      "EditDate": null,
      "EditBy": null,
      "BundleParent": null,
      "MasterExpertise": null,
      "PriceSchema": null,
      "Appointments": [],
      "InverseBundleParent": [],
      "InvoiceDetails": []
    },
    {
      "Id": 17,
      "Name": "Anxiety Disorder",
      "Description": null,
      "MasterExpertiseId": 6,
      "PriceSchemaId": 8,
      "IsBundled": false,
      "BundleParentId": null,
      "SellingPrice": 250000.00,
      "ProductCount": 1,
      "IsEnabled": true,
      "IsDeleted": false,
      "StartDate": null,
      "EndDate": null,
      "AddDate": "2020-09-29T13:29:52.228043+07:00",
      "AddBy": null,
      "EditDate": null,
      "EditBy": null,
      "BundleParent": null,
      "MasterExpertise": null,
      "PriceSchema": null,
      "Appointments": [],
      "InverseBundleParent": [],
      "InvoiceDetails": []
    }
  ]
};
